### ISSUE TITLE
Embed YouTube guides in the relevant help pages

### ISSUE THREAD

**Issue by arikfr** [getredash/website#321] opened 2019-11-28 09:59 UTC

**Comment by susodapop** [comment] 2020-01-15 02:35
I think we can use the [gatsby-remark-embed-youtube](https://www.gatsbyjs.org/packages/gatsby-remark-embed-youtube/?=embed%20yout) for this.

**Comment by susodapop** [comment] 2020-04-24 18:22
Duplicate of https://github.com/getredash/website/issues/282

**Closed by susodapop** 2020-04-24 18:22 UTC
Labels: Documentation
